# Generated by Django 4.2.1 on 2023-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField()),
                ('apartments', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('year_built', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
