# Generated by Django 4.2.1 on 2023-05-31 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_house_delete_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=80)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house')),
            ],
        ),
    ]
