# Generated by Django 4.2.1 on 2023-06-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('payed', 'Оплачен'), ('not_payed', 'Не оплачен')], default='not_payed', max_length=10),
        ),
    ]
