# Generated by Django 4.1.1 on 2023-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('payed', 'Оплачен'), ('not_payed', 'Не оплачен')], default='not_payed', max_length=10),
        ),
    ]
