# Generated by Django 4.1.1 on 2023-06-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.house'),
        ),
    ]
