# Generated by Django 4.2.1 on 2023-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('full_text', models.TextField(max_length=500, verbose_name='Описание услуги')),
                ('summ_uslug', models.TextField(verbose_name='Стоимость')),
            ],
        ),
    ]
