# Generated by Django 4.2.1 on 2023-05-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidyrabot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Виды услуг', 'verbose_name_plural': 'Виды услуг'},
        ),
    ]
