# Generated by Django 4.2.1 on 2023-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyrabot', '0002_alter_artiles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='full_text',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
    ]
