# Generated by Django 4.1.1 on 2023-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyrabot', '0003_alter_artiles_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='full_text',
            field=models.TextField(verbose_name='Текст Обращения'),
        ),
        migrations.AlterField(
            model_name='artiles',
            name='summ_uslug',
            field=models.TextField(verbose_name='Адрес, номер телефона'),
        ),
        migrations.AlterField(
            model_name='artiles',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Фамилия, Имя, Отчество'),
        ),
    ]
